### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jershell** [ionspin/kotlin-multiplatform-bignum#101]
**Describe the bug**

w: skipping ../com.ionspin.kotlin/bignum-linux/0.1.5/bb1ea2db83c116b118147efe55b35b01ae0e82bd/bignum.klib. The abi versions don't match. Expected '[22]', found '17'. The library produced by 1.3.61-release-13550 compiler

**To Reproduce**
1. Run Clion 
2. Create kotlin/native helloWorld app by wizard
3. Add the library
4. Run build

**Expected behavior**
Build success

**Platform**
 - [Native, Linux]

**Comment by jershell** [comment]
`plugins {
    kotlin("multiplatform") version "1.3.72"
}

repositories {
    mavenCentral()
}

kotlin {
    // For ARM, preset function should be changed to iosArm32() or iosArm64()
    // For Linux, preset function should be changed to e.g. linuxX64()
    // For MacOS, preset function should be changed to e.g. macosX64()
    linuxX64("HelloWorld") {

        binaries {
            // Comment the next section to generate Kotlin/Native library (KLIB) instead of executable file:
            executable("HelloWorldApp") {
                // Change to specify fully qualified name of your application's entry point:
                entryPoint = "sample.helloworld.main"
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(kotlin("stdlib-common"))
                implementation("com.ionspin.kotlin:bignum:0.1.5")
            }
        }
    }
}

// Use the following Gradle tasks to run your application:
// :runHelloWorldAppReleaseExecutableHelloWorld - without debug symbols
// :runHelloWorldAppDebugExecutableHelloWorld - with debug symbols
`

**Comment by ionspin** [comment]
Hi @jershell, I have never officially released 1.3.72 version, and currently I am preparing a release for 1.4. But there is a snapshot version that you can use that was built for 1.3.72
`com.ionspin.kotlin:bignum:0.1.6-1.3.72-SNAPSHOT`
You'll need to add sonatype snapshot to your repositories:
```repositories {
    mavenCentral()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }
}```
I'll leave this issue open until kotlin 1.4 is released and appropriate bignum 1.4  to go with it.

**Comment by jershell** [comment]
> you can use that was built for 1.3.72
com.ionspin.kotlin:bignum:0.1.6-1.3.72-SNAPSHOT...
> 

Thank you!

**Comment by ionspin** [comment]
Version 0.2.0 built with Kotlin 1.4.0 was just released, should be available in a couple of hours on Maven, so with that this issue is completely resolved.
