### ISSUE TITLE
BigInteger.toByteArray should prefer ByteArray over Array<Byte>

### ISSUE THREAD

**Issue by kevincianfarini** [ionspin/kotlin-multiplatform-bignum#104]
**Is your feature request related to a problem? Please describe.**
On the JVM, primitive arrays have to be represented as their own specific types. For example, `byte[]` in Java corresponds to `ByteArray` in Kotlin. Right now, `BigInteger.toByteArray()` returns `Array<Byte>` which is the boxed type. It's like `Byte[]` in Java. This results in a lot of unboxing of values when working with the data. 

**Describe the solution you'd like**
convert from `BigInteger.toByteArray(): Arra<Byte>` to `BigInteger.toByteArray(): ByteArray`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ionspin** [comment]
Hi @kevincianfarini ,
The whole byte array conversion API will be overhauled before the next release, because currently it's a mess.To demonstrate why it's a mess, you'll see that UByte conversions are actually split just as you describe:
```
    override fun toByteArray(): Array<Byte> {
        return arithmetic.toByteArray(magnitude, sign)
    }

    override fun toTypedUByteArray(endianness: Endianness): Array<UByte> {
        return arithmetic.toTypedUByteArray(magnitude, endianness)
    }

    override fun toUByteArray(endianness: Endianness): UByteArray {
        return arithmetic.toUByteArray(magnitude, endianness)
    }
```
The other thing is that endianness is also not clearly exposed.

With that said, it would help if you could share what is your use case for byte array conversions, as that would expand my perspective on the needs for this API and possibly help model it properly.

Thanks for reporting!

**Comment by kevincianfarini** [comment]
In a personal project, corbit, I have a need for a `ByteString` type. The ByteString type from Okio as of right now is not sufficient, so I've been rolling my own until that improves. Both Okio ByteString and corbit BinaryString are backed by `ByteArray`. 

Corbit is a BitTorrent implementation in Kotlin. BitTorrent relies heavily on data verification with SHA-1. Therefore, I've been implementing a multiplatform SHA-1 on `BinaryString`. SHA-1 digest values are 160 bits long and require bitshifts, which I felt was perfect for BigInteger. 

In order to get the values from the boxed variants to the unboxed ones (on JVM), every time I calculate the SHA-1 hash of a BinaryString I need to unbox 20 bytes. 

I'm not sure of any performance implications yet, but I suspect there will be some. A BitTorrent download has to verify sometimes tens of thousands of pieces using SHA-1.
