### ISSUE TITLE
Comparison of two negative BigDecimals incorrect

### ISSUE THREAD

**Issue by skolson** [ionspin/kotlin-multiplatform-bignum#114]
Using the current 0.1.6 snaphot, for this code snippet:
```
val testVal = BigDecimal.fromShort(Short.MIN_VALUE)
val highLimit = BigDecimal.fromInt(Int.MIN_VALUE)
val lowLimit = BigDecimal.fromInt(Int.MIN_VALUE)
val biggerThanMax = compare(highLimit )
val lessThanMin = compare(lowLimit)
```
testVal is -32768
highLimit is 2.147483647E+9
lowLimit is -2.147483648E+9
biggerThanMax = -1 which is correct
lessThanMin = -1 which is incorrect, should be 1

Side note: I'm planning on doing a pull request for the Narrowing issue likely tomorrow (8/6/2020). If you like I can fix this one also as part of that pull request. I debugged in and think I see the fix but don't know until I see it work :-)  This bug prevents a unit test on the Narrowing changes from working, since it believes precision will be lost as it thinks -32768 is more negative than -2.147483648E+9 which is wrong.   
#111

**Comment by ionspin** [comment]
Sounds great! I'm fine with putting everything in one pull request since in this situation. Thanks!

**Comment by ionspin** [comment]
Hey @skolson, this was actually a bug in BigInteger comparison not in BigDecimal, so I went and fixed it as it was bothering me a lot that I messed it :)
