### ISSUE TITLE
Conversion to double off by power of 10

### ISSUE THREAD

**Issue by skolson** [ionspin/kotlin-multiplatform-bignum#130]
Given this JVM snippet:

        val testDouble = 999111.999111
        val testBig = BigDecimal.fromDouble(testDouble)
        val newDouble = testBig.doubleValue(true)
        assertEquals(testDouble, newDouble, 0.0)

assert should work, but assert fails:
java.lang.AssertionError: 
Expected :999111.999111
Actual   :9991119.99111

I haven't tried other scenarios yet, have not finished debugging. This was using 0.2.0. 

The problematic line in BigDecimal.kt is:

                this.significand.longValue(true).toDouble() / double10pow[exponent.toInt()]

In debugger, state of BigDecimal before this line is this:

this = {BigDecimal@859} "9.99111999111E+5"
 precision = 12
 precisionLimit = 0
 roundingMode = {RoundingMode@864} "NONE"
 significand = {BigInteger@865} "999111999111"
 exponent = 5
 scale = -1
 usingScale = false
 decimalMode = null

It looks like this should work but it doesn't.  Still digging.

Environment is AS 4.1, Kotlin 1.4.10

**Comment by skolson** [comment]
Wait I was looking at this wrong. This line does need to change. I'm gonna try to come up with a new one.

**Comment by skolson** [comment]
Ok how about this.  The exponent is the wrong divisor in this case of a positive exponent. Changing 
```this.significand.longValue(true).toDouble() / double10pow[exponent.toInt()]```
to this:
```this.significand.longValue(true).toDouble() / double10pow[precision - 1 - exponent.toInt()]```
works in the current case, but requires tweaking the surrounding IF statement.  I'm gonna test this out in other scenarios to see if this is a general solution or introduces other issues :-)

**Comment by skolson** [comment]
I think this replacement for the existing return statement in the doubleValue function is a candidate for a general solution. If this looks ok, lemme know and I will do a pull request and some real testing:
```
        val divExponent = this.significand.numberOfDecimalDigits().toInt() - 1 - exponent.toInt()
        return if (divExponent >= 0 && divExponent < double10pow.size) {
                this.significand.longValue(true).toDouble() / double10pow[divExponent]
            } else
                this.toString().toDouble()
        }
```

**Comment by skolson** [comment]
Issue is growing, during testing of above fix, found a case where fromDouble is off by power of 10. Will be submitting a pull request with changes to DoubleValue, fromDouble, and new unit tests in BigDecimalNarrowingTest. The old unit test was only testing edge (MIN/MAX) cases, so the bugs I'm finding didn't have test coverage.

**Comment by skolson** [comment]
Hmm. fromDouble has code that tries to drop trailing zeroes from a double string before passing it to parseStringWithMode, That assumes however that there is no exponent on the end :-).  The test double value that this code fails on was
``'9.991119991110001E-10'''  which this code changes to ``'9.991119991110001E-1`'', removing an important trailing zero :-).  Will fix.

**Comment by skolson** [comment]
I have a commit ready for a pull request, waiting for gradle "allTests" task to finish. Once that completes successfully I will submit a pull request for this issue.

**Comment by skolson** [comment]
Darn, I just messed up the pull request (#131) and didn't get the "Resolves #130" in the front of the description. Also the title is way too verbose. Now I can't seem to edit it to fix this error, Sorry...

**Comment by skolson** [comment]
Lol, figured out how to fix title and description.

**Comment by ionspin** [comment]
Hey Steven, nice catch and thanks for the pull request, this really helps as I haven't had time lately to work on bignum library. The fixes will appear in version "0.2.3-SNAPSHOT" as soon as the travis job is done. I'll keep from releasing stable 0.2.3 for some time (lets say for one month, until 23 of November) to see if we can get more potential bugfixes or some improvements as well. Is it okay for you to use snapshot version until then? @skolson

**Comment by skolson** [comment]
No prob, works for me.  I'm getting close to having the Kotlin MP wrapper for Sqlcipher I've been working on functional for a few platforms. It uses BigDecimal from this lib for all its non-integer fields. So once that's done, the arithmetic, decimal mode, scale, and other functions of BigDecimal will get pounded pretty good.  It won't test really big number operations much, but should be enough to find any more bugs in typical usage. If I hit more issues I'll post again, but it won't be for a couple weeks or so :-)   Thanks!

**Comment by ionspin** [comment]
>  I'm getting close to having the Kotlin MP wrapper for Sqlcipher I've been working on functional for a few platforms. It uses BigDecimal from this lib for all its non-integer fields. So once that's done, the arithmetic, decimal mode, scale, and other functions of BigDecimal will get pounded pretty good.

That's great! Looking forward to seeing the library used properly!
