### ISSUE TITLE
[Help needed] Standalone library jar gives ClassNotFoundException at runtime

### ISSUE THREAD

**Issue by shadowsheep1** [ionspin/kotlin-multiplatform-bignum#140]
**Describe the bug**
Using this library to build a **JVM multiplatform library**, if you create a *standalone jar* when you add this jar as library in an Android project it compiles well but at runtime we got a `ClassNotFound` exception.

**To Reproduce**
1. Creata a Multiplatform library project using IntelliJ kotlin multiplatform library template.
2. Add this library as dependency and the build  a public function that uses `BigDecimal` like that:
```kotlin
class Test {
    fun test(value: String): Int {
        return BigDecimal.parseString(value).toBigInteger().intValue()
    }
}
```
3. Generate a standalone jar archive for the library.
4. Add this jar to an Android project that usis the above open function.
5. Compile the android app module (it builds okay).
6. Launch the app on simulator (crash for `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ionspin/kotlin/bignum/decimal/BigDecimal;`).

**Expected behavior**
The Android app didn't crash

**Platform**
 -  JVM, Android

**Additional context**
- https://discuss.kotlinlang.org/t/kotlin-native-dependency-is-not-accessible-at-runtime-on-the-target-platform/18547
- https://stackoverflow.com/questions/65039841/kotlin-native-compile-jar-and-framework

Could you help me understand why? I didn't see this behavior in other 3rd party libraries. Only with this if a try to add my library using this in an Android project.

For more reference, I was able to use the library in a JVM Application by generate the jar archive by the **Build Artifacts** function by forcing this librar to be added in the archive. But if I use this same jar archive in an Android project I still get the `ClassNotFoundException`.

I've seen that only metadata jar is included in the jar...

![image](https://user-images.githubusercontent.com/16268789/100798770-60a7aa80-3424-11eb-9745-ba18aa3b7b44.png)

This is not quite a kind of bug, but a request to understend why we got this behavior. Maybe it could depends on how this library is publish on sonatype?

**Comment by ionspin** [comment]
Hi @shadowsheep1 what you are getting when you generate your standalone jar is a jar that doesn't contain any transitive dependencies, in this case bignum library. If you want to use a jar you would need to create a fat jar that would contain all transitive dependencies of your project. Unfortunately that is a question more suited for stackoverflow than github. Also I don't know how to do that :) One direction to investigate would be gradle shadow plugin (https://github.com/johnrengelman/shadow).

Another solution would be to directly add bignum jvn to your android build.gradle.kts alongside your jar.

```
implementation("com.ionspin.kotlin:bignum-jvm:0.2.3")
```

So to sun things up, this is normal behaviour for any jvm jar, and it's expected that you get no class def exception. I hope my comments helped you a bit. I'll close this issue now.

**Comment by shadowsheep1** [comment]
Hey @ionspin thanks anyway! It seems that no one uses jar anymore.. me too ;)
