### ISSUE TITLE
Testing BigInteger's bitwise xor operation with randomised input occasionally produces incorrect results 

### ISSUE THREAD

**Issue by fullkomnun** [ionspin/kotlin-multiplatform-bignum#145]
**Describe the bug**
Randomised tests expose use-cases in which xor bitwise operation is inconsistent with Java's BigInteger

**To Reproduce**
Steps to reproduce the behaviour:
I amended BigInteger63JavaBitwiseTest::`Test random xor` to:
```kotlin
    @Test
    fun `Test random xor`() {
        val seed = 1
        val random = Random(seed)
        val jobList: MutableList<Job> = mutableListOf()
        for (i in 1..Int.MAX_VALUE step 3001) {
            jobList.add(
                GlobalScope.launch {
                    val a = ULongArray(2) { random.nextULong() }
                    val b = ULongArray(1) { random.nextULong() }
                    singleXorTest(a, b)
                }
            )
        }
        runBlocking {
            jobList.forEach { it.join() }
        }
    }
```
And about 25% of total tests produces incorrect result that differ from Java's BigInteger's.

observations:
- If I use an array length of 1 for both - all test succeed
- If I limit values to UInt by using `random.nextUInt().toULong()` - all test succeed
- Kotlin xor output is always consistent so `operand xor mask == mask xor operand` (based on my [PR](https://github.com/ionspin/kotlin-multiplatform-bignum/pull/144))
- If both operand and mask have an array of size 2 with random ULong values - same bugs occur but I provided the simplest reproducible use-case

Sample Data:
operand - 165113626007271252408312729491020585537
operand - kotlin magnitude : [-3844891364232652223, -545088871305293897]
operand - java magnitude   : [2084026951, -1620432933, -895208532, -487450047]

mask - 18101283144754361246
mask - kotlin magnitude : [-345460928955190370]
mask - java  magnitude : [-80433891, -1915128930]

multiplatform xor - 165113626007271252406505777807814781407
multiplatform xor  - kotlin magnitude : [3571528989416319455, -545088871305293897]
multiplatform xor  - java  magnitude : [2084026951, -1620432933, -1315922255, 1865116127]

java xor - 165113626007271252397282405770960005599
java xor- kotlin magnitude : [3571528989416319455, 8678283165549481910, 1]
java xor - java  magnitude : [2084026951, -1620432933, 831561393, 1865116127]

**Expected behaviour**
The result are expected to be a such that it is consistent with Java's BigInteger so:
(operand xor mask).toJavaBigInteger() == operand.toJavaBigInteger().xor(mask.toJavaBigInteger())

**Platform**
 JVM

**Additional context**
I think that these randomised tests are great for identifying such inconsistencies with Java's BigInteger and are useful for all bitwise operations and arithmetic implementations.

**Comment by ionspin** [comment]
Great catch, I'll look into it more tomorrow, thanks!

**Comment by fullkomnun** [comment]
performing xor in 32 bit arithmetics using conversions results in expected outcome but when using xor with 63 bit arithmetics output is incorrect. Example for doing xor with 32 bit arithmetic:
```kotlin
val result = BigInteger63Arithmetic.convertFrom32BitRepresentation(BigInteger32Arithmetic.xor(BigInteger63Arithmetic.convertTo32BitRepresentation(operand), BigInteger63Arithmetic.convertTo32BitRepresentation(mask)))
```

**Comment by ionspin** [comment]
Hey @fullkomnun, sorry for the delay, I haven't had time to look into this before today. I think xor is actually working fine here, there is a small mistake in your test, when you are generating random values to test with you are using nextULong
```
val a = ULongArray(2) { random.nextULong() }
val b = ULongArray(1) { random.nextULong() }
 ```
This creates arrays with 64 bit values, but the arithmetic is working on 63bit length words. So randomly, that bit will be set to 1 when it's expected to be 0 and then the results can be unpredictable.

Changing your test just to shift right one bit makes it pass.

```
    @Test
    fun `Test random xor`() {
        val seed = 1
        val random = Random(seed)
        val jobList: MutableList<Job> = mutableListOf()
        for (i in 1..Int.MAX_VALUE step 3001) {
            jobList.add(
                GlobalScope.launch {
                    val a = ULongArray(2) { random.nextULong() shr 1 }
                    val b = ULongArray(1) { random.nextULong() shr 1 }
                    singleXorTest(a, b)
                }
            )
        }
        runBlocking {
            jobList.forEach { it.join() }
        }
    }
```
But your issue also brings up that the current random xor test is completely wrong, so I'll use you updated test instead.

Also I'd like to thank you for spending time and providing a very insightful issue report, the way you structured it and provided sample values makes looking into issues much easier!

**Comment by ionspin** [comment]
Merge #147 handled this issue, I just forgot to mention it there so it didn't auto close.
