### ISSUE TITLE
Bug during parsing string "0.00" to BigDecimal

### ISSUE THREAD

**Issue by matt400m** [ionspin/kotlin-multiplatform-bignum#148]
**Describe the bug**
After invoke "0.00".toBigDecimal() I get BigDecimal("0.")

**To Reproduce**
run test:
```
import io.kotest.matchers.shouldBe
import kotlin.test.Test
import kotlin.text.toBigDecimal
import com.ionspin.kotlin.bignum.decimal.toBigDecimal as lib

class Test {

    @Test
    fun `test big decimal`() {
        val toBigDecimal = "0.00".toBigDecimal()
        toBigDecimal.toEngineeringString() shouldBe "0.00"

        val toBigDecimal2 = "0.00".lib()
        toBigDecimal2.toPlainString() shouldBe "0.00"

    }
}
```

**Expected behavior**
toPlainString() should return "0.00"

**Platform**
 - JVM, iOS

**Comment by ionspin** [comment]
Thanks for reporting the issue! Fix addresses the missing zero (`0.`) but toPlainString() which actually calls `toStringExpanded` will not work exactly as it does in JVM bigDecimal, it will return `0`, not `0.0`
On the other hand, using normal `toString` will return `0.0`
