### ISSUE TITLE
KDoc comments for RoundingMode.ROUND_HALF_[AWAY/TOWARDS]_ZERO are swapped

### ISSUE THREAD

**Issue by okarmazin** [ionspin/kotlin-multiplatform-bignum#156]
https://github.com/ionspin/kotlin-multiplatform-bignum/blob/fa306ad22a29e6cab5c3ac5641147ec5ce9252fa/bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/DecimalMode.kt#L48

**Comment by ionspin** [comment]
Thanks for reporting!
