### ISSUE TITLE
BigDecimal addition producing incorrect results

### ISSUE THREAD

**Issue by cowmanjoe** [ionspin/kotlin-multiplatform-bignum#175]
**Describe the bug**
When using this library with Kotlin/JS, I've found that incorrect results are produced when adding two BigDecimal numbers together. It appears to put the decimal place in the wrong spot. 

**To Reproduce**
```
        val x = BigDecimal.ZERO
        val y = BigDecimal.parseString("0.00007")

        val z = x + y
```

z equals 7.0 after this runs.

**Expected behavior**
z should equal 0.00007, or perhaps (but probably not) just a rounded 0 value.

**Platform**
JS

**If JS (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome Version 90.0.4430.93

**Comment by ionspin** [comment]
Hi @cowmanjoe could you share which version of the library are you using? This issue (if it is the same issue) was fixed in #174 but the fix is only available in 0.3.1-SNAPSHOT version

**Comment by cowmanjoe** [comment]
Ah, that's great. I am using 0.2.8. Is there a way to use this snapshot version? It doesn't appear to be present in the maven repository

**Comment by ionspin** [comment]
Yeah,

**Comment by cowmanjoe** [comment]
Thank you!
