### ISSUE TITLE
Use constructor overloading for BigInteger

### ISSUE THREAD

**Issue by RdeWilde** [ionspin/kotlin-multiplatform-bignum#18]
**Is your feature request related to a problem? Please describe.**
You have to write longer method names than just the constructor

**Describe the solution you'd like**
Apply constructor overloading instead of `fromFloat`, `fromInt`, `parseString` etc

**Describe alternatives you've considered**
NA

**Additional context**
Constructor overloading

**Comment by RdeWilde** [comment]
This may do the trick, except for the String-type. https://github.com/paycoin-com/kotlin-multiplatform-bignum/commit/79e4bb31407921a39c1bf1249142b1916ee707cf

Disclaimer: untested.

**Comment by ionspin** [comment]
Thanks, that is something I had in mind as well, I think I should be able to add it this evening.

**Comment by RdeWilde** [comment]
No hurries, better do it right ;-) Glad if it helps
