### ISSUE TITLE
BigInteger.longValue() doesn't take sign into account

### ISSUE THREAD

**Issue by dsvdmeer** [ionspin/kotlin-multiplatform-bignum#186]
**Describe the bug**
When converting a `BigInteger` with a negative value to a `Long` using `longValue()`, it produces a positive result.

**To Reproduce**
```kotlin
val bigInteger = (-12L).toBigInteger()
val asLong = bigInteger.longValue(exactRequired = true)
assertEquals(-12L, asLong) // Fails here
```

**Expected behavior**
In the above example, `asLong` should equal `-12`.

**Platform**
 - JVM (Running unit tests)

**Comment by ionspin** [comment]
@dsvdmeer Thanks for reporting the issue! The fix should be available in snapshot version once the master branch build request is completed, in an hour or so barring any issues.
