### ISSUE TITLE
ArithmeticException on repeating decimal when scale is set

### ISSUE THREAD

**Issue by sproctor** [ionspin/kotlin-multiplatform-bignum#231]
`BigDecimal.divide()` should not throw ArithmeticException at https://github.com/ionspin/kotlin-multiplatform-bignum/blob/873a770296389e77e9cb3cbe8b402e05f5b1062b/bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt#L1276 if scale is set.

**Comment by ionspin** [comment]
Thanks for reporting!

**Comment by ionspin** [comment]
Fixed in 9175878d4b7e6b, will be available in 0.3.7-SNAPSHOT once the build completes.
