### ISSUE TITLE
Division test failures are being ignored

### ISSUE THREAD

**Issue by sproctor** [ionspin/kotlin-multiplatform-bignum#245]
Exceptions thrown from coroutines are not being caught in the test context and so tests are passing despite having failures.

https://github.com/ionspin/kotlin-multiplatform-bignum/blob/main/bignum/src/jvmTest/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimalJvmTest.kt#L415

This test is failing. If you remove the `launch` it will properly trigger the failure

**Comment by ionspin** [comment]
Thanks for reporting!
