### ISSUE TITLE
0 precision is unintuitive

### ISSUE THREAD

**Issue by sproctor** [ionspin/kotlin-multiplatform-bignum#257]
**Describe the bug**
The docs claim that 0 means unlimited precision. This isn't true when scale is set. 0 precision is worthless. My suggestion is that when precision is 0 and scale is set in the `DecimalMode` for an operation, default to `max(decimalPrecision, other.decimalPrecision)`.

**Comment by ionspin** [comment]
Precision turned out to be an awful API, my idea is to completely drop it in 0.4 and just keep scale or if no scale set unlimited precision

**Comment by ionspin** [comment]
I'm closing this as https://github.com/users/ionspin/projects/2 and initial issue #259 has been created to tackle DecimalMode/Scale API.
