### ISSUE TITLE
Can't Parse BigDecimal from Response API

### ISSUE THREAD

**Issue by abdhilabs** [ionspin/kotlin-multiplatform-bignum#264]
Hi, I got this error, when receive data from API.
Is this library only can parse from String to BigDecimal?

![Screenshot 2023-07-14 at 07 32 27](https://github.com/ionspin/kotlin-multiplatform-bignum/assets/101545982/998e67c5-8512-479d-bba5-4be2c581ed4a)

**Comment by ionspin** [comment]
Hi @abdhilabs, BigDecimal doesn't support kotlinx serialization directly, but I did provide custom serializers some time ago, it's mentioned in the readme here https://github.com/ionspin/kotlin-multiplatform-bignum#serialization

Hope this helps. Also I am closing this as it's not an issue.
