### ISSUE TITLE
Round half to even on 0.5 should be 0 and not 1

### ISSUE THREAD

**Issue by glureau** [ionspin/kotlin-multiplatform-bignum#277]
**Describe the bug**
Source of truth: https://en.wikipedia.org/wiki/Rounding (I'm not expert in rounding so if there's something better, tell me)
In this source I can read that the rounding "half to even" of 0.5 should be 0. That's not the case, in pseudo-code I have:
- **roundHalfToEven(0.5, scale = 0) = 1 // Should be 0**
- roundHalfToEven(0.05, scale = 1) = 0 // OK
- roundHalfToEven(0.005, scale = 2) = 0 // OK

**To Reproduce**
This test is failing:
```kotlin
    @Test
    fun `rounding half even`() {
        assertEquals(
            0,
            BigDecimal
                .parseString("0.5")
                .roundToDigitPositionAfterDecimalPoint(0, roundingMode = RoundingMode.ROUND_HALF_TO_EVEN)
                .intValue(),
        )
    }
```

**Expected behavior**

roundHalfToEven(0.5, scale = 0) == 0

**Platform**
 - Tested on JVM

**Comment by ionspin** [comment]
Thanks for reporting!
