### ISSUE TITLE
Wrong ByteArray representation for BitInteger(0)

### ISSUE THREAD

**Issue by TemMax** [ionspin/kotlin-multiplatform-bignum#280]
**Describe the bug**
`java.math.BigInteger#toByteArray` returns ByteArray(0) (size == 1) when `bignum.BigInteger#toByteArray` returns an empty ByteArray.

**Platform**
 - JVM

**Comment by ionspin** [comment]
Thanks for reporting, fix shoulde be available in snapshot soon.
