### ISSUE TITLE
Missing BigInteger operations

### ISSUE THREAD

**Issue by ionspin** [ionspin/kotlin-multiplatform-bignum#3]
**Describe the bug**
BigInteger class is missing some operators that would make it closer to the Java big int (since we are looking at kotlin extended java BigInteger as inspiration amongst others). 

This issue does not include prime operations, single bit operations or modular arithmetic, which are all also missing at this moment.

**To Reproduce**
1. Try to find absolute value method in BigInteger class
2. Fail at finding it

**Expected behavior**
I expected a abs() method.

**Platform**
 - Common

**Additional context**
Methods to add:
- ~Power - pow(int)~
- ~Greatest common divisor - gcd(BigInteger)~ But the most unoptimizied implementation possible
- ~Absolute value - abs()~
- ~Negate - negate()~
- ~Signum function - signum()~
- ~Square root~

**Comment by ionspin** [comment]
Still GCD and SQRT left to do

**Comment by RdeWilde** [comment]
I created a seperate issue for `modInverse`: https://github.com/ionspin/kotlin-multiplatform-bignum/issues/14

**Comment by ionspin** [comment]
Everything implemented, currently using naive implementations, but the goal for 0.1.0 is full functionality
