### ISSUE TITLE
Move point by pow of 10 - BigDecimal.movePointRight

### ISSUE THREAD

**Issue by RdeWilde** [ionspin/kotlin-multiplatform-bignum#50]
**Is your feature request related to a problem? Please describe.**
No, just a feature request

**Describe the solution you'd like**
Implement (something similiar to) BigDecimal.movePointRight
While doing that, probably add movePointLeft too.
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#movePointRight-int-

**Describe alternatives you've considered**
Scaling by power of 10 while maintaining positive position.

**Additional context**
https://stackoverflow.com/questions/25454734/what-is-the-difference-between-bigdecimal-movepointright-and-scalebypoweroften

**Comment by RdeWilde** [comment]
This is probably the same as `BigInteger.shl` and `.shr`, but not implemented in BigDecimal/BigNumber.

**Comment by ionspin** [comment]
Huh, never noticed that one, I guess you'd do it if you want to change the just the exponent without running the actual calculations. Do you have a particular use case in mind for this? 

I'd be inclined to provide a different solution, something like `.copy(significand, exponent, mathContext)` which would have default values of the current BigDecimal, so you could do something like
```
val a = 123.toBigDecimal()
val b = a.copy(exponent = a.exponent + 2)
``` 
And the b would be 12300, replicating the movePointToRight functionality but also giving more flexibility.

The same thing is possible at the moment by using the BigDecimal constructor, but it is not as nice as having a dedicated `.copy()`

**Comment by RdeWilde** [comment]
I think the name `movePointToRight` is a little more explicit. Maybe implement the `copy`-approach and just "alias" `movePointToRight` and `movePointToLeft` to it?

I tried your last suggestion, using the `BigDecimal` constructor, but I don't know how I should get it to work.
`BigDecimal` wants a `BigInteger` as a constructor argument, so I tried this.

```
val original = (123.45).toBigDecimal()
val moved = BigDecimal(original.significand, original.exponent + 1) // movePointToRight(1)
```
Which results in an error, as the corresponding constructor is private.
How do I fix this?

**Comment by ionspin** [comment]
Ah, sorry I forgot the constructor was private, this works though
```
    @Test
    fun testMovePoint() {
        val original = (123.45).toBigDecimal()
        val moved = BigDecimal.fromBigIntegerWithExponent(original.significand, original.exponent + 1)
        assertTrue {
            moved == (1234.5).toBigDecimal()
        }
    }
```
