### ISSUE TITLE
Couldn't import the library

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#51]
Hello, i am trying to use the library, but couldn't. I can successfully import other kotlin multiplatform library.
here is my build.gradle

    apply plugin: 'kotlin-multiplatform'

    kotlin {
    targets {
        final def iOSTarget = presets.iosX64 // Simulator

        fromPreset(iOSTarget, 'iOS') {
            binaries {
                framework('SharedCode')
            }
        }

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain {
            dependencies {
                api 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation ("com.ionspin.kotlin:bignum:0.1.0")
            }
        }

        androidMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib'
        }
    }
    }

In my commonMain folder, i try to use following function

    val bigIntegerExtension = 234L.toBigInteger() // unresolved reference

What am I missing here? Please help

Android gradle plugin version : 3.5.0
Gradle version : 5.4.1
kotlin version : 1.3.41

**Comment by ionspin** [comment]
You are probably missing
```enableFeaturePreview("GRADLE_METADATA")```
In your settings.gradle

You can see the discussion around it here (https://github.com/Kotlin/kotlinx.coroutines/issues/564#issuecomment-456565452) , and also how to avoid using metadata by specifying all dependencies manually.
