### ISSUE TITLE
Support for kotlin 1.3.50

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#59]
Hi! thank you so much for providing this library! Overall this library has helped our team so much! 

Is there any timeline for another release version? Now we are facing a performance issue, and also is there any plan to support kotlin 1.3.50 soon? 

Thanks!

**Comment by ionspin** [comment]
Hey, I'm happy to hear you found the library useful, even in these early stages! There is no strict timeline for releases, but a rough roadmap is tracked through github projects which you can find here https://github.com/ionspin/kotlin-multiplatform-bignum/projects

I'm currently working on implementing more efficient algorithms such as Karatsuba, Toom-Cook, FFT, for multiplications, although depending on your use case these might not bring any visible improvements. 

The master branch is already on 1.3.50 but I haven't released it yet, I can really commit to a date, but I'll try to push that release in next couple of weeks.

Can you share your use-case for the library, or a code snippet? The better user perspective I get, the better I can optimize the library and the APIs in the future.

**Comment by avjiang** [comment]
@ionspin 

Thanks for the detailed info! We are using the library for the Decimal calculation. We cannot use Double to do it because the precision details. So far the library is doing good. However, in our use case, if there are 40+ elements inside the array, the calculation might take some time in the iOS side (runtime). But overall the library is performing well! 

You are helping people out there like me by providing this library, and we are so grateful! Thank you so much :)
