### ISSUE TITLE
Fix 32bit variant Toom-Cook and Karatsuba

### ISSUE THREAD

**Issue by ionspin** [ionspin/kotlin-multiplatform-bignum#62]
**Describe the bug**
Both Karatsuba and Toom-Cook in 32bit variants have bugs

**To Reproduce**
Run appropriate multiplication tests

**Expected behavior**
There are no bugs.

**Comment by kavanmevada** [comment]
check this Karatsuba implementation written in kotlin-native https://github.com/kavanmevada/kotlin-native-bignum

**Comment by kavanmevada** [comment]
can you tell me, which is fastest algorithm for division ?
• Single Limb Division	  	
• Basecase Division	  	
• Divide and Conquer Division	  	
• Block-Wise Barrett Division	  	
• Exact Division	  	
• Exact Remainder	  	
• Small Quotient Division

**Comment by ionspin** [comment]
Hi @kavanmevada thanks for the suggestion, I'll have a look, although I already have karatsuba working for 63-bit implementation, I just haven't had the time to look into 32-bit implementation and why is it failing. For your division question, unfortunately I don't know, yet :) I'll be working on division improvements soon-ish, so I might get back to you on that.

**Comment by kavanmevada** [comment]
I seen your library. I'm Impressed. You implemented lot. I started mine by goal of implementing RSA which lead me to all basic arithmetic for large numbers. Almost most implemented. Remaining powerMod which needed fast division and fast mod functions.

In some research paper I read Basecase Division and Divide and Conquer Division fast. But I still not understand algorithms correctly. I'm noob in cryptography so I mostly understood algorithms by examples. And I can't find proper examples of those methods.

**Comment by ionspin** [comment]
I started from the same point about a year, year and half ago and I still find myself in the same situation often. 

Here is a comparison of different algorithms from 2003: http://bioinfo.ict.ac.cn/~dbu/AlgorithmCourses/Lectures/Lec5-Fast-Division-Hasselstrom2003.pdf

For cryptography I really suggest going through Cryptography I by Dan Boneh on Coursera. 

Also look through Crypto subreddit for some great resources.
