### ISSUE TITLE
Doesn't work for mingw target.

### ISSUE THREAD

**Issue by johanneskraem3r** [ionspin/kotlin-multiplatform-bignum#70]
**Is your feature request related to a problem? Please describe.**
Tried to add this as a dependency in a MP project building for windows ( mingw ). 
It doesn't seem to resolve the bignum library. 
It does find bignum-metadata.

**Describe the solution you'd like**
Support for mingw ?

**Describe alternatives you've considered**
I have to admit that I'm quite new to Kotlin MP, but reading the readme of this library, 
it sounds like I should be able to use this on all Kotlin platforms. 
But it seems to not work for windows builds. Can you confirm?

**Comment by ionspin** [comment]
Hi @johanneskraem3r, you are right, I haven't had mingw targets set up previously, so even though the library doesn't need any source code changes (hopefully!) I need to build and publish mingw targets. I need to set up windows build machine so I guess I'll have some time over weekend to get to it and publish it as a snapshot release.

**Comment by johanneskraem3r** [comment]
I see. Thanks for the quick response. If it's trivial to build on windows, I can offer to build the mingw targets as I'm running already on windows. Would need a bit of help to set it all up, but if it's just a few steps and you can tell me how to do it, I can try?

**Comment by ionspin** [comment]
Thanks for offering to build it, but I still need to set up Travis to do that with each pull request, and the maven releases are signed in my local environment before uploading to maven central.

 If you want to build it locally and try it out before I'm done with the enviroments and publishing, you can check out the `add-mingw` branch, and then run `gradlew.bat publishMingwX64PublicationToMavenLocal publishMingwX86PublicationToMavenLocal` (or similar, check `gradlew.bat tasks` to be sure which one is it) which should build the library and publish it to your local maven repository so you can use it from your project (don't forget to add mavenLocal() to gradle repositories build config in your project)

If you hit any problems please share them, as I'll probably be experiencing them myself when I get to setting up my local windows enviroment.
