### ISSUE TITLE
Exception when converting negative numbers

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#78]
**Describe the bug**
There is an exception thrown when processing negative numbers
 
**To Reproduce**

    println((-6.0).toBigDecimal().toStringExpanded().toDouble()) 

**Expected behavior**

    The library will process the number same as positive numbers

Version : 0.1.5-SNAPSHOT

![image](https://user-images.githubusercontent.com/19270457/70975095-36aa8a80-20e4-11ea-91f0-f83fcaf43092.png)

Image above is the reference

**Comment by ionspin** [comment]
Thanks for reporting this issue @avjiang! It will be published in 0.1.5-SNAPSHOT as soon as Travis build finishes. Make sure you have the latest snapshot before testing, as gradle can cache older snapshots longer than presumed.

**Comment by avjiang** [comment]
ty for the fast response @ionspin ! gonna try that soon

**Comment by avjiang** [comment]
@ionspin , there is another bug (throwing exception) in this sample code of negative value 

    println((-0.006).toBigDecimal().toStringExpanded().toDouble())

**Comment by ionspin** [comment]
Hey @avjiang could you add the exception stacktrace, I can't reproduce the latest problem. Also I just noticed the cache question, either try with `--refresh-dependencies` which would redownload all dependancies, or delete `~/.gradle/caches/modules-2/files-2.1/com.ionspin.kotlin/` folder, although that might break something else in gradle.

**Comment by avjiang** [comment]
@ionspin 

Here is the stacktrace

![image](https://user-images.githubusercontent.com/19270457/71791622-a7541f80-3070-11ea-84d8-ecb91d416012.png)

btw, how to run the command you provided above? I try to run it in my Android Studio terminal but it stated no command found. Please help.. Thanks!

**Comment by ionspin** [comment]
That looks strange, it's trying to fetch an older version of the snapshot (a very old in fact), that is probably why you are also seeing the exception. Why is it trying to get the older version, I don't know. 
You could try to add this to your `build.gradle`

```
dependencyManagement {
    resolutionStrategy {
        cacheChangingModulesFor 0, 'seconds'
    }
}
```
It should force gradle to fetch the SNAPSHOT marked dependencies every time (but I've seen it not work sometimes).

**Comment by avjiang** [comment]
Now i am facing this error, but the date seems newer 

![image](https://user-images.githubusercontent.com/19270457/71875043-5de1fe00-315e-11ea-8d5c-3071e6745575.png)

Looks like i wont be able to proceed without you to release it in new version. This snapshot thing is too buggy at my side. It is really hard for my team to proceed as now we cannot resolve the negative numbers. 

Thank you so much for your help all this time @ionspin ! Really appreciate it

**Comment by ionspin** [comment]
Hey @avjiang I released version 0.1.5 with the fixes, hope it fixes problems on your side.

**Comment by avjiang** [comment]
@ionspin ty so much for the help. Really appreciate it. This is my first time dealing with gradle and all these stuffs, and didn't expect it to be so buggy.

Thanks!

**Comment by ionspin** [comment]
I'm glad I can help!
