### ISSUE TITLE
Incorrect result after rounding decimal point

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#86]
**Describe the bug**
Incorrect result from function `roundToDigitPositionAfterDecimalPoint`

**Expected behavior**
Follow the decimal point digit 

![image](https://user-images.githubusercontent.com/19270457/72321017-ca6c7800-36dd-11ea-8266-e8c7318e161a.png)

**Comment by ionspin** [comment]
Thanks for reporting! Fixed in 0.1.6-SNAPSHOT

**Comment by avjiang** [comment]
@ionspin 

another incorrect figures :

    assertEquals(9.17111007690947.toBigDecimal().roundToDigitPositionAfterDecimalPoint(2, RoundingMode.ROUND_HALF_AWAY_FROM_ZERO),9.17.toBigDecimal())
    assertEquals(9.7825174153701.toBigDecimal().roundToDigitPositionAfterDecimalPoint(2, RoundingMode.ROUND_HALF_AWAY_FROM_ZERO),9.78.toBigDecimal())

**Comment by ionspin** [comment]
I tested these two with latest 0.1.6-SNAPSHOT, and they were returning expected results.

**Comment by avjiang** [comment]
Same good old bug again.. lol

![image](https://user-images.githubusercontent.com/19270457/72591524-4ca5a800-393b-11ea-95a1-974a1fc9d97f.png)

**Comment by ionspin** [comment]
Yeah, that looks correct. Could you check which version of gradle are you using for the project? The version is usually in the `./gradle/wrapper/gradle-wrapper.properties` starting from your project root directory.

**Comment by ionspin** [comment]
And also if you are not using the latest (6.0.1) version, you could try by setting this inside the gradle.properties file:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-bin.zip`

**Comment by avjiang** [comment]
hi @ionspin 

sorry for my late reply. all the while i am not using 6.0.1 gradle version, but after changed the version, it is working in my side already. not sure that is the problem or not. Will see how it would be in the future. 

will inform u again once there is any update. thanks :)
