### ISSUE TITLE
Incorrect Result From Negative Double

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#90]
**Describe the bug**
Negative figures round gives incorrect result

**Expected behavior**
Return 0 

**To Reproduce**
1. Operation
2. Values to reproduce issue

![image](https://user-images.githubusercontent.com/19270457/74497948-fc117280-4f19-11ea-90a3-29d0a29039fa.png)

**Comment by ionspin** [comment]
Hey @avjiang, thanks for reporting this! I'll look into it as soon as I can.
